### ISSUE TITLE
no more wget nor curl. How to have an healthcheck ?

### ISSUE THREAD

**Issue by stanthewizzard** [marcopeocchi/yt-dlp-web-ui#147]
hello
latest version is curl less.

is there a way to have an healthcheck ?
thanks

**Comment by marcopeocchi** [comment]
hello @stanthewizzard,

healthcheck from the docker container or healthcheck of the container itself?

**Comment by stanthewizzard** [comment]
Container itself

**Comment by clickbg** [comment]
I just hit that one too, my fix was to build the container locally with netcat in it:

```
FROM marcobaobao/yt-dlp-webui
RUN apk add --no-cache netcat-openbsd
```

And run it like this from compose:

```
yt-dlp:
build:
  context: /root/admin/docker/build
  dockerfile: yt-dlp.docker
---- the rest of your settings
```

Hope this help!
