### ISSUE TITLE
Docker Compose ERROR

### ISSUE THREAD

**Issue by Fenizlater** [marcopeocchi/yt-dlp-web-ui#155]
Docker gives this error when i create container with docker compose and i dont know how is the failure, i create directory config and config.yml but the same error

someone knows what is the problem?

2024/06/02 09:14:06  [1;41m config  [0m open /config/config.yml: no such file or directory
time=2024-06-02T09:14:06.510Z level=INFO msg="yt-dlp-webui started" address=0.0.0.0:3033
time=2024-06-02T09:14:06.511Z level=INFO msg="sucessfully persisted session"

**Comment by marcopeocchi** [comment]
Hello @Fenizlater,

it's not necessary creating the `config.yml` file.
Here's an example `docker-compose.yml`
```yml
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    ports:
      - 3033:3033
    volumes:
      - <your dir>:/downloads
      - /var/yt-dlp-webui/config:/config # replace /var/yt-dlp-webui/config with your directory
    restart: unless-stopped
```
