### ISSUE TITLE
Default file permissions

### ISSUE THREAD

**Issue by rogueai** [marcopeocchi/yt-dlp-web-ui#159]
Hi, I wanted to ask if there's a way to set default permissions for downloaded files?
I'm using the docker image and I've set the correct UID and GID and that works fine, but it seems all files get `777` permissions, which is undesirable.

Thanks!

**Comment by marcopeocchi** [comment]
Hello @rogueai,

**File permission are not handled by my web-ui.** 
I've tested on my system, with correct UID and GID, files are set to `644`.

Maybe it's a misconfiguration on something else? How is mounted the volume where you're storing the downloaded files?

**Comment by rogueai** [comment]
Hi @marcopeocchi, 

Ok perhaps I should mention, I've set the container to run with the GID/UID of the user with access to the mounted volume, here's the gist of it:
```
services:
  yt-dlp:
    image: ghcr.io/marcopeocchi/yt-dlp-web-ui:latest
    volumes:
      - ./downloads:/downloads
    user: 123:123
```
This allows the container to create files under that folder, but then I get all files with `777` permissions. I'm not ruling out a misconfiguration on my side, so I'll try to reproduce it elsewhere and see if it happens consistently.

Thanks!
