### ISSUE TITLE
RPC Auth in Docker Compose

### ISSUE THREAD

**Issue by MajorTomDE** [marcopeocchi/yt-dlp-web-ui#167]
Hey,

I tried my best, but it seems that I’m too stupid to configure RPC Auth in Docker Compose.

Could you extend your Docker Compose Example with RPC Auth configuration?

Thanks so much, Tom

**Comment by marcopeocchi** [comment]
I will add it to the `README.md` later but...

To configure RPC Auth with docker you need to expose the `/config` volume and create the `config.yml` configuration file inside of it.

`config.yml`
```yaml
# RPC settings
require_auth: true # enables authentication
username: ciao
password: ciao # will be changed to hash version in the future
```

Later you will be "greet" by this screen:
![Screenshot 2024-07-15 alle 10 05 40](https://github.com/user-attachments/assets/610f7042-9141-486a-99e4-d3ae9d6b2a05)

Press login and then provide your credentials.
