### ISSUE TITLE
Homepage custom API?

### ISSUE THREAD

**Issue by chronomac** [marcopeocchi/yt-dlp-web-ui#276]
I noticed that you asked for widget support over on the Homepage repo: https://github.com/gethomepage/homepage/discussions/4445

You said that you had made your own custom API. Can you share that code here, if you don't mind? Thanks in advance.

**Comment by marcopiovanello** [comment]
Sure no problem. I will upload it to a gist

**Comment by chronomac** [comment]
@marcopiovanello Apologies for my complete ignorance here but after updating the container what should I use for the widget config within homepage? This one specifically https://gethomepage.dev/widgets/services/customapi/

I have this currently set in my services.yaml and I'm getting `API Error: Invalid data`

```
    - yt-dlp-web-ui:
        href: http://[internal IP]:3033
        server: my-docker
        container: yt-dlp-web-ui
        description: YouTube preservation
        widgets:
          - type: customapi
            url: http://yt-dlp-web-ui:3033
            mappings:
               - field: pending
                 label: pending
```
